spring:
  application:
    name: booking-service
  grpc:
    server:
      port: 9090
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

app:
  kafka:
    topics:
      booking-history:
        name: booking-history-topic

logging:
  level:
    io.grpc: DEBUG
    com.hotelio: DEBUG

monolith:
  userservice:
    url: http://hotelio-monolith:8080/api/users
  hotelservice:
    url: http://hotelio-monolith:8080/api/hotels
  reviewservice:
    url: http://hotelio-monolith:8080/api/reviews
  promocodeservice:
    url: http://hotelio-monolith:8080/api/promos