spring:
  application:
    name: booking-service
  grpc:
    server:
      port: 9090
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
feign:
  client:
    config:
      connectTimeout: 5000
      readTimeout: 5000
      loggerLevel: full

kafka:
  bootstrap-servers: kafka:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retries: 3

app:
  kafka:
    topics:
      booking-history:
        name: booking-history-topic

monolith:
  userservice:
    url: http://hotelio-monolith:8080/api/users
  hotelservice:
    url: http://hotelio-monolith:8080/api/hotels
  reviewservice:
    url: http://hotelio-monolith:8080/api/reviews
  promocodeservice:
    url: http://hotelio-monolith:8080/api/promo-codes